var config = {
  texts: [
    "Today is...",
    "as beautiful as other days",
    "but you realize",
    "another year has gone",
    "in a blink of the eyes",
    "however",
    "Do you know..?",
    "today is just special",
    "so special to you",
    "that's why",
    "Let's make it...",
    "the best celebration ever",
    "and let me share...",
    "a piece of happiness to you",
    "I made all this...",
    "as a birthday present to you",
    "thanks for being there",
    "thanks for the friendship we made",
    "thanks for everything",
    "I wish you all the best",
    "May your life be at ease",
    "May all your wishes come true",
    "Remember",
    "your ambitions",
    "you live as a free bird...",
    "flying in the blue sky",
    "Now things are different...",
    "real story of your life",
    "is just about to begin",
    "indeed...",
    "this life is not easy as we thought",
    "but...",
    "don't worry",
    "don't be afraid",
    "because...",
    "you are not alone in this world",
    "because...",
    "this year will be better",
    "and I hope",
    "you'll find...",
    "happiness along the way",
    "keep your spirits up",
    "enjoy every single moment...",
    "that you experiecne today",
    "fill it with your most beautiful smile",
    "and make it the best memory..",
    "lastly...",
    "I'd like to wish you one more time",
    "a very happy birthday",
  ],

  desc: {
    turn_on: "Turn On Lights",
    play: "Play Music",
    bannar_coming: "Let's Decorate",
    balloons_flying: "Fly With Balloons",
    cake_fadein: "Most Special Cake Ever",
    light_candle: "Light Candle",
    wish_message: "Happy Birthday",
    story: "A message for you",
  },
};
